MvcStok/Controllers/MusterilerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcStok.Models.Entity;

namespace MvcStok.Controllers
{
    public class MusterilerController : Controller
    {
        MvcDbStokEntities db = new MvcDbStokEntities(); 
        public ActionResult Index(string p)
        {
            var degerler = from d in db.TBLMUSTERILER select d;
            if(!string.IsNullOrEmpty(p))
            {
                degerler = degerler.Where(m=>m.MUSTERIAD.Contains(p));
            }
            return View(degerler.ToList());  
            //var value = db.TBLMUSTERILER.ToList();
            //return View(value);
        }
        [HttpGet]
        public ActionResult YeniMusteri() 
        {
            return View();
        }
        [HttpPost]
        public ActionResult YeniMusteri(TBLMUSTERILER p2)
        {
            if(!ModelState.IsValid)
            {
                return View("YeniMusteri");
            }
            db.TBLMUSTERILER.Add(p2);
            db.SaveChanges();
            return View();
        }
        public ActionResult SIL(int id)
        {
            var musteri = db.TBLMUSTERILER.Find(id);
            db.TBLMUSTERILER.Remove(musteri);
            db.SaveChanges();
            return RedirectToAction("Index");

        }
        public ActionResult MusteriGetir(int id)
        {
            var mus = db.TBLMUSTERILER.Find(id);
            return View("MusteriGetir",mus);
        }
        public ActionResult Guncelle(TBLMUSTERILER p1)
        {
            var musteri = db.TBLMUSTERILER.Find(p1.MUSTERIID);
            musteri.MUSTERIAD = p1.MUSTERIAD;
            musteri.MUSTERISOYAD = p1.MUSTERISOYAD;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MvcStok/Views/Musteriler/Index.cshtml
@using MvcStok.Models.Entity
@model List<TBLMUSTERILER>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@using (Html.BeginForm("Index", "Musteriler", FormMethod.Get))
{
    <p>
         <b>Aranacak Müşteri Adı:</b> @Html.TextBox("p")
        <input type="submit" value="Ara" />
    </p>
}



<table class="table table-bordered">
    <tr>
        <th>MÜSTERI ID</th>
        <th>MÜSTERI ADI</th>
        <th>MÜSTERI SOYADI</th>
        <th>SİL</th>
        <th>GÜNCELLE</th>
        <th>ALERT</th>
    </tr>

    <tbody>
        @foreach (var mrn in Model)
        {
            <tr>
                <th>@mrn.MUSTERIID</th>
                <td>@mrn.MUSTERIAD</td>
                <td>@mrn.MUSTERISOYAD</td>
                <td><a href="/MUSTERILER/SIL/@mrn.MUSTERIID" class="btn btn-danger">SİL</a></td>
                <td><a href="/MUSTERILER/MusteriGetir/@mrn.MUSTERIID" class="btn btn-success">GÜNCELLE</a></td>
                <td>@Html.ActionLink("Sil Butonu", "SIL", new { id = mrn.MUSTERIID }, new { @class = "btn btn-warning", onclick = "return confirm('Gerçekten Silmek İstiyor Musunuz?')" })</td>
            </tr>

        }
    </tbody>


</table>
<a href="/Musteriler/YeniMusteri/" class="btn btn-primary">YENİ MÜŞTERİ EKLE</a>

MvcStok/Views/Musteriler/MusteriGetir.cshtml
@model MvcStok.Models.Entity.TBLMUSTERILER
@{
    ViewBag.Title = "MusteriGetir";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@using (Html.BeginForm("Guncelle", "Musteriler", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(m => m.MUSTERIID)
        @Html.TextBoxFor(m => m.MUSTERIID, new { @class = "form-control" })
        <br/>
        @Html.LabelFor(m=>m.MUSTERIAD)
        @Html.TextBoxFor(m=>m.MUSTERIAD , new { @class = "form-control" })
        <br/>
        @Html.LabelFor(m=>m.MUSTERISOYAD)
        @Html.TextBoxFor(m=>m.MUSTERISOYAD, new { @class = "form-control" })
    </div>
    <div>
        <button class="btn btn-warning">Müşteri Güncelle</button>

    </div>
}

MvcStok/Views/Musteriler/YeniMusteri.cshtml
@model MvcStok.Models.Entity.TBLMUSTERILER
@{
    ViewBag.Title = "YeniMusteri";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<form method="post" class="form-group">
    @*<div>
            <label>Müşteri Adı</label>
            <input type="text" class="form-control" name="MUSTERIAD" />
        </div>*@
    <div>
        <label>Müşteri Adı</label>
        @Html.TextBoxFor(m => m.MUSTERIAD, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.MUSTERIAD, "", new { @style = "color:green" })
    </div>
    <div>
        <label>Müşteri Soyadı</label>
        <input type="text" class="form-control" name="MUSTERISOYAD" />
    </div>
    <div style="margin-top:10px">
        <button class="btn btn-info" id="btn1">Müşteri Ekle</button>
    </div>
    <script>
        $('#btn1').click(function () {
            alert('Müşteri Ekleme İşlemi Yapıldı....!');
        });

    </script>


</form>